name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode Test
      uses: devbotsxyz/xcode-test@v1.1.0
      with:
        project: Example/RFIBANHelper.xcodeproj
        scheme: RFIBANHelper
        configuration: Debug
        destination: platform=iOS Simulator,OS=14.0,name=iPhone 11
    - name: Perform Cocoapod lib lint validation
      uses: readefries/cocoapod-lint-github-action@v1-beta
      with:
        podspec: RFIBAN-Helper.podspec
        allow-warnings: true

