name: Release an update to Cocoapods

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true      
      - name: Install Node dependencies
        run: npm install
      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Sed new version in Podspec
        run: sed -i "" -e 's|<LIB_VERSION>|${{ version_bump.new_tag }}|g' RFIBAN-Helper.podspec
      - name: Push update to Cocoapods when merging to main        
        run: exec pod trunk push RFIBAN-Helper.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
